openapi: 3.1.0
x-stoplight:
  id: i8i3l2jkf1i6e
info:
  title: timmew
  version: '1.0'
  description: 'https://timmew.commew.net で利用するREST API'
servers:
  - url: 'http://localhost:5757'
    description: local
paths:
  '/users/{userId}':
    parameters:
      - schema:
          type: integer
        name: userId
        in: path
        required: true
        description: Id of an existing user.
    get:
      summary: Get User Info by User ID
      tags: []
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Get User Alice Smith:
                  value:
                    id: 142
                    firstName: Alice
                    lastName: Smith
                    email: alice.smith@gmail.com
                    dateOfBirth: '1997-10-31'
                    emailVerified: true
                    signUpDate: '2019-08-24'
        '404':
          description: User Not Found
      operationId: get-users-userId
      description: Retrieve the information of the user with the matching user ID.
    patch:
      summary: Update User Information
      operationId: patch-users-userId
      responses:
        '200':
          description: User Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Updated User Rebecca Baker:
                  value:
                    id: 13
                    firstName: Rebecca
                    lastName: Baker
                    email: rebecca@gmail.com
                    dateOfBirth: '1985-10-02'
                    emailVerified: false
                    createDate: '2019-08-24'
        '404':
          description: User Not Found
        '409':
          description: Email Already Taken
      description: Update the information of an existing user.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                  description: 'If a new email is given, the user''s email verified property will be set to false.'
                dateOfBirth:
                  type: string
            examples:
              Update First Name:
                value:
                  firstName: Rebecca
              Update Email:
                value:
                  email: rebecca@gmail.com
              Update Last Name & Date of Birth:
                value:
                  lastName: Baker
                  dateOfBirth: '1985-10-02'
        description: Patch user properties to update.
  /user:
    post:
      summary: Create New User
      operationId: post-user
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                New User Bob Fellow:
                  value:
                    id: 12
                    firstName: Bob
                    lastName: Fellow
                    email: bob.fellow@gmail.com
                    dateOfBirth: '1996-08-24'
                    emailVerified: false
                    createDate: '2020-11-18'
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                dateOfBirth:
                  type: string
                  format: date
              required:
                - firstName
                - lastName
                - email
                - dateOfBirth
            examples:
              Create User Bob Fellow:
                value:
                  firstName: Bob
                  lastName: Fellow
                  email: bob.fellow@gmail.com
                  dateOfBirth: '1996-08-24'
        description: Post the necessary fields for the API to create a new user.
      description: Create a new user.
  /accounts:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-accounts
    post:
      summary: ''
      operationId: postAccounts
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties: {}
      description: アカウント登録を行うAPI
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          description: 'Authorization: Basic の形で送信する'
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OpenIdProvider'
            examples:
              Example 1:
                value:
                  sub: '10769150350006150715113082367'
                  provider: google
        description: ''
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
    Account:
      title: account
      x-stoplight:
        id: d81ba26a96905
      type: object
      description: アカウント
      examples:
        - id: 1
          name: NekoKoneko
          openIdProvider:
            - sub: '10769150350006150715113082367'
              provider: google
        - id: 2
          name: MyCat
          openIdProvider:
            - sub: '999999999999999999999999999'
              provider: google
            - sub: lineid99999999999999999999999
              provider: line
      properties:
        id:
          type: number
          minimum: 1
          description: アカウントの識別子
        name:
          type: string
          description: アカウント名
        openIdProviders:
          type: array
          items:
            $ref: '#/components/schemas/OpenIdProvider'
      required:
        - id
        - name
        - openIdProviders
    OpenIdProvider:
      title: OpenIdProvider
      x-stoplight:
        id: e1ambjwj1ixhm
      type: object
      description: 登録・ログイン時に利用するOpenIdProvider
      properties:
        sub:
          type: string
          example: '10769150350006150715113082367'
          description: OpenIdProviderのユーザー識別子
        provider:
          type: string
          pattern: /^(google|line|apple|facebook)$/
          description: 'OpenIdProviderの種類を表す .e.g. google, line'
      required:
        - sub
        - provider
      examples:
        - sub: '10769150350006150715113082367'
          provider: google
        - sub: lineid99999999999999999999999
          provider: line
